### ISSUE TITLE
windows anki: the password is not correct

### ISSUE THREAD

**Issue by hqzxjczx** [tsudoko/anki-sync-server#33]
ankidroid is no problem when upload or down load from anki-sync-server. but when i want to uplaod or download data from anki-sync-server, then windows anki always pop up the  tooltip 'the password is not correct'. I have no idea about this.
it is more instresting that , if the acount is registed on the anki web, there are no problem to sync data. but the data was backup on the anki web, even though you have created the same acount by the command './ankisyncctl.py username'.  
however, if the acount is build by command './ankisyncctl.py adduser username' and  is not registed on the anki web, when you sync data , it will pop up the tooltip 'the password is not correct'. I am sure the password is correct, if not i can't sync data for ankidroid.
please give me a hand, thank you. @tsudoko .

**Comment by tsudoko** [comment]
Are you sure you've followed the [client setup instructions](https://github.com/tsudoko/anki-sync-server#setting-up-anki) correctly? From what you're saying it seems like Anki is still using AnkiWeb to sync instead of your server.

You can check which server Anki is using to sync by pressing Ctrl+Shift+; (semicolon), typing in `print(anki.sync.SYNC_BASE)`, pressing Ctrl+Enter and checking the URL. It should match whatever you have entered in the custom sync server addon.

**Comment by hqzxjczx** [comment]
it's my problem. Didn't followed the client setup instructions. when I follow the client setup instructions, it has been solved. I can sync data by ankidroid or windows anki from anki-sync-server. Thank you @tsudoko .
