### ISSUE TITLE
AnkiDroid Syncing error 404

### ISSUE THREAD

**Issue by jnslmk** [tsudoko/anki-sync-server#43]
Anki Desktop 2.1.14
AnkiDroid 2.8.4

I am using anki sync server behind a NGINX reverse proxy.
My setup works with the Anki desktop client with the SyncRedirector Add-on and the following URLs defined:
```
{
    "msyncUrl": "http://ankisync.my-domain.org/msync/",
    "syncUrl": "http://ankisync.my-domain.org/sync/"
}
```
It also works via local network with the IP configured directly:
```
{
    "msyncUrl": "http://192.168.0.x:27701/msync/",
    "syncUrl": "http://192.168.0.x/sync/"
}
```

However, I tried both variants with and without a trailing slash at the end of the URL and get the following error with all configurations:
```
Syncing error, type: 404, message: Not Found
```

Accessing http://ankisync.my-domain.org/ via mobile web browser displays `Anki Sync Server` correctly.

I'd be grateful for hints on how to debug this issue further.

**Comment by tsudoko** [comment]
Does the sync URL field contain `/sync/`? [It shouldn't, as AnkiDroid appends `sync/` on its own.](https://github.com/ankidroid/Anki-Android/blob/9bda85fb3b81b94ad37be1be6269aed3d1acac64/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java#L425) Otherwise, looking at ankisyncd and nginx logs might help.

**Comment by jnslmk** [comment]
Thank you! Yes, the URL field ended with `/sync`. Removing it solved the problem. It also showed in the nginx logs
