### ISSUE TITLE
Plan to support v2 scheduler?

### ISSUE THREAD

**Issue by TooYoungTooSimp** [tsudoko/anki-sync-server#54]
I've encountered an error like #47 
the solution introduced in #48 just explicitly points out no support of v2 scheduler

Is there any plan to add support for v2 scheduler?

**Comment by tsdko** [comment]
Not unless I switch to v2 scheduler or someone else volunteers to support it.

The error is likely caused by this `if` statement:
https://github.com/tsudoko/anki-sync-server/blob/2bfccf7fa4af87545f009729ff6e84934c6fde0b/ankisyncd/sync_app.py#L114-L115

[Anki rewrites non-`/meta` error messages heavily](https://github.com/ankitects/anki/blob/b5a8d3f47c43894d28708b7bd38d20517aba4b41/aqt/sync.py#L153-L197), so the original message is obscured. You could try removing the block; syncing might work (it did last time I checked v2 sync, but that was a long time ago), and if something breaks and you can fix it, PRs are welcome.

**Comment by TooYoungTooSimp** [comment]
I have made some changes and tested on my devices.
All things work perfectly.
PR #53 is updated.
